name: glowup_vibes
description: Goated Dart language. Glowup Vibes is a Dart package that adds some "internet slang" to Dart vocabulary.
version: 1.0.0
topics: [meme]
repository: https://github.com/renancaraujo/glowup_vibes
issue_tracker: https://github.com/renancaraujo/glowup_vibes/issues
homepage: https://github.com/renancaraujo/glowup_vibes

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason_logger: ^0.2.10

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

